### PR TITLE
Add fullstop

### PR DESCRIPTION
**Pull request by GitMuslim**

### CODE REVIEW

**Comment by GitMuslim** [comment]
@isabelroses

**Comment by isabelroses** [comment]
> @isabelroses

Hey @GitMuslim, I can't approve this I'm not a staff/core member on this repo.

**Comment by GitMuslim** [comment]
> > @isabelroses
> 
> Hey @GitMuslim, I can't approve this I'm not a maintainer on this repo.

oh ok, @sgoudham

**Comment by sgoudham** [comment]
Personally, I think a normal full stop after a file extension looks weird which is why I didn't add one when refactoring these docs and why I'll be closing this.

Also please refrain from pinging maintainers of the organisation for "aesthetic" changes such as this.

**Comment by GitMuslim** [comment]
Alright

**Pull request closed without merging**
