### PR TITLE
feat: explicitly track current & past maintainers

### PR DESCRIPTION
**Pull request by sgoudham**
This PR kicks off our maintainer audit, aiming to explicitly track the maintainers of our ports. I will add more and more maintainers when I have free time, happy for @catppuccin/staff to get involved and push to this PR.

Two new keys for each port have been added:
- `current-maintainers`: The list of active maintainers for the port.
- `past-maintainers`: The list of maintainers who have previously maintained the port.

The biggest concern that I have at the moment is the `port.yml`'s file size/length, as the yaml anchors for the GitHub usernames will increase it by quite a bit. Unfortunately, they can't be extracted out to another file either.

### CODE REVIEW

**Review by sgoudham — COMMENTED** [review]
I think this PR is as good as it gets™️

As mentioned on discord, I think the `current-maintainers` array is _mostly_ accurate and the `past-maintainers` array does need some work, but I think we'll be relying on maintainers to PR themselves in if they find that they are missing.

## Next Steps

1. Close #2316 
2. Raise a PR on `catppuccin/website` to ingest this data and populate the maintainers table.
3. Raise a PR on `catppuccin/catppuccin` to filter out the `archived` ports into a different section.
4. Raise a PR on `catppuccin/catppuccin` to automate the additions/removals of maintainers via the GitHub API.
5. Revamp the documentation to mention how to add ports into the `ports.yml` (along with whiskers and everything else)

**Review by andreasgrafen — APPROVED** [review]
Lookin' good! Thanks for your efforts. <3

**Review by backwardspy — APPROVED** [review]
any road followed precisely to its end leads precisely nowhere. climb the mountain just a little bit to test that it's a mountain. from the top of the mountain, you cannot see the mountain.

**Review by nullishamy — APPROVED** [review]
ok soud goudham good pr

**Review by backwardspy — CHANGES_REQUESTED** [review]
> not now, i'm watching netflix

hammy, 2024

**Review by nullishamy — CHANGES_REQUESTED** [review]
> I was actually thinking of rewriting Catppuccin and using a different palette

the saud, 2024

i cant believe he would do this to us.

**Comment by backwardspy** [comment]
image

**Comment by sgoudham** [comment]
image

**Review by andreasgrafen — CHANGES_REQUESTED** [review]
Re-checking this again; I got one request:
I would really appreciate it if you could make it have ear holes. Do you think this is a possibility?
Thanks in advance! <3

**Pull request merged**
