### PR TITLE
fix: rename sideberry to sidebery in ports.yml

### PR DESCRIPTION
**Pull request by backwardspy**
typo in the port name. vscode also autoformatted the file, if you don't like that i'll change it back

### CODE REVIEW

**Comment by mustafakhalaf-git** [comment]
@thismoon homie gotta see this

**Review by sgoudham — APPROVED** [review]
LGTM!

**Comment by nekowinston** [comment]
whoops

**Comment by thismoon** [comment]
oh sorry about this, i always misspell it like that

**Pull request merged**
