### PR TITLE
chore(maintainers): add Matthias to `sublime-text`

### PR DESCRIPTION
**Pull request by MatthiasPortzel**
I just edited this file, let me know if I did this right.

CC: @ghostx31

### CODE REVIEW

**Comment by uncenter** [comment]
Is @ghostx31 no longer a maintainer? If so, you'll want to move @ghostx31 to `past-maintainers`, and otherwise you should add your name as an additional entry after theirs.

**Comment by MatthiasPortzel** [comment]
Thanks for checking. He hasn't been using Sublime but he has been addressing issues on GitHub, so I we can keep him in the list here.

**Comment by uncenter** [comment]
You'll also want to rename this PR to follow the conventional commits specification, something like `docs(sublime-text): add matthias as current maintainer`.

**Comment by uncenter** [comment]
[](url)

> Thanks for checking. He hasn't been using Sublime but he has been addressing issues on GitHub, so we may as well keep him in the list here. (I originally removed him intentionally, but changed my mind.)

It looks like they are listed as a contributor in the README anyway so unless they step down I think they are a still a maintainer :)
image

**Comment by MatthiasPortzel** [comment]
> You'll also want to rename this PR to follow the conventional commits specification, something like `docs(sublime-text): add matthias as current maintainer`.

No problem, edited.

**Comment by uncenter** [comment]
> > You'll also want to rename this PR to follow the conventional commits specification, something like `docs(sublime-text): add matthias as current maintainer`.
> 
> No problem, edited.

(Nitpick but usually we have the first character after the `<type>(<scope>):` be lowercase - like `docs(sublime-text): add Matthias as a maintainer`.)

**Comment by ghostx31** [comment]
Feel free to remove me, now that you're here to maintain this. Thanks for taking this up!

**Review by sgoudham — APPROVED** [review]

**Pull request merged**
