### PR TITLE
docs: remove `0.1.3` -> `0.2.0` translation table

### PR DESCRIPTION
**Pull request by noobieyuh**
add a link to docs/translation-table.md in docs/README.md🪴Index

### CODE REVIEW

**Comment by sgoudham** [comment]
That translation table document isn't actually relevant anymore so I was looking towards removing it since it will continue to exist in commit history 🤔

**Comment by noobieyuh** [comment]
Oh, okay :) I just thought it would make sense to add it to the docs/README.md, but if it isn't relevant anymore and is planning to be removed, then it doesn't really matter adding it to docs/README.md then. When will docs/translation-table.md be removed?

**Comment by sgoudham** [comment]
This could be the PR to remove it ;)

**Comment by noobieyuh** [comment]
Whoops! Sorry about that.

**Review by sgoudham — APPROVED** [review]
Thanks!

**Pull request merged**
